name: DevSecOps
'on':
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch: null

env:
  GITHUB_PUSH_BEFORE_SHA: '${{ github.event.before }}'
  GITHUB_PUSH_BASE_SHA: '${{ github.event.base }}'
  GITHUB_PULL_BASE_SHA: '${{ github.event.pull_request.base.sha }}'
  GITHUB_DEFAULT_BRANCH: '${{ github.event.repository.default_branch }}'
  GITGUARDIAN_API_KEY: '${{ secrets.GITGUARDIAN_API_KEY }}'

jobs:

  Auto_Code_Review:
    name: Code-Review-DevSkim
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v1
        with:
         sarif_file: devskim-results.sarif
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DevSkim-artifact
          path: ${{ github.workspace }}

  Secrets_Scan:
    name: SecretsScan-GitGuardian
    runs-on: ubuntu-latest
    needs:
      - Auto_Code_Review
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        with:
          args: -v --all-policies --show-secrets 
        env:
          GITHUB_PUSH_BEFORE_SHA: '${{ github.event.before }}'
          GITHUB_PUSH_BASE_SHA: '${{ github.event.base }}'
          GITHUB_PULL_BASE_SHA: '${{ github.event.pull_request.base.sha }}'
          GITHUB_DEFAULT_BRANCH: '${{ github.event.repository.default_branch }}'
          GITGUARDIAN_API_KEY: '${{ secrets.GITGUARDIAN_API_KEY }}'



         

  Software_Comp_Analysis_Debricked:
    name: Software-Comp-Analysis-Debricked
    runs-on: ubuntu-latest
    needs:
      - Secrets_Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: debricked/actions/scan@v1
        env:
          USERNAME: '${{ secrets.DEBRICKED_USERNAME }}'
          PASSWORD: '${{ secrets.DEBRICKED_PASSWORD }}'


  Software_Comp_Analysis_DepCheck:
    name: Software-Comp-Analysis-OWASPDEPCHECK
    runs-on: ubuntu-latest
    needs:
      - Secrets_Scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download Dep Check tool
      run:  wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.2.2/dependency-check-6.2.2-release.zip
    - name: Install the tool and run it
      run: unzip dependency-check-6.2.2-release.zip && ls -l && dependency-check/bin/dependency-check.sh -s .
        
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
          name: depcheck-artifact
          path: ${{ github.workspace }}     

  SAST:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    needs:
     - Software_Comp_Analysis_Debricked
     - Software_Comp_Analysis_DepCheck
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports




           

  
        
  Build_Image_Docker_Test:
    name: Build-Push-Image-Docker
    runs-on: ubuntu-latest
    needs:
      - SAST    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: misterbert0ni/testimage
          tags: 'v1, latest, ${{ github.sha }}'
          registry: docker.io
          dockerfile: ./Dockerfile
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          

 

  #  SCA_safety:
  #     name: Source Composition Analysis (Safety)
  #     runs-on: ubuntu-latest
  #     needs:
  #       - Secrets_Scan
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@master
  #       - name: Safety Check
  #         uses: aufdenpunkt/python-safety-check@master
  #         env:
  #           DEP_PATH: /requirements.txt
  #